### Задача 1

Создайте датафрейм, сохранив его в отдельном Excel файле Output data.xlsx, со следующими свойствами:
- Столбец month должен быть преобразован в столбец days, содержащий абсолютно точное количество дней, которое человек проживает по текущему адресу. При преобразовании предполагайте, что сегодня 2000-01-01.
- Добавьте столбец с доходом на одного члена семьи (income_per_family_member). При расчете четко опишите в комментарии, какие предположения вы сделали для определения количества членов семьи.
- Выберите свой собственный критерий определения уровня дохода, разбейте данные согласно выбранному критерию, записав результат в новый столбец income_level. Подробно опишите выбранный критерий.
- Добавьте столбец, содержащий отношение средних годовых трат по кредитной карте к годовому доходу (share_of_annual_expentitures).
- Итоговый датафрейм должен содержать информацию только о людях, для которых share_of_annual_expenditures превышает 100%.
- Отсортируйте итоговый датафрейм таким образом, чтобы первые строки содержали информацию о самозанятых людях. Далее, отдельно для самозанятых и не самозанятых, отсортируйте датафрейм в соответствии с share_of_annual_expenditures (от большего к меньшему).

In [315]:
#Импортируем оригинальную таблицу
import pandas as pd
frame = pd.read_csv('data_assignment2.csv', header=0, sep = '/')
frame

,card,reports,age,income,share,expenditure,owner,selfemp,dependents,months,majorcards,active
0,yes,0,37.66667,4.5200,0.033270,124.983300,yes,no,3,54,1,12
1,yes,0,33.25000,2.4200,0.005217,9.854167,no,no,3,34,1,13
2,yes,0,33.66667,4.5000,0.004156,15.000000,yes,no,4,58,1,5
3,yes,0,30.50000,2.5400,0.065214,137.869200,no,no,0,25,1,7
4,yes,0,32.16667,9.7867,0.067051,546.503300,yes,no,2,64,1,5
5,yes,0,23.25000,2.5000,0.044438,91.996670,no,no,0,54,1,1
6,yes,0,27.91667,3.9600,0.012576,40.833330,no,no,2,7,1,5
7,yes,0,29.16667,2.3700,0.076434,150.790000,yes,no,0,77,1,3
8,yes,0,37.00000,3.8000,0.245628,777.821700,yes,no,0,97,1,6
9,yes,0,28.41667,3.2000,0.019780,52.580000,no,no,0,65,1,18
10,yes,0,30.50000,3.9500,0.078025,256.664200,yes,no,1,24,1,20
11,no,0,42.00000,1.9800,0.000606,0.000000,yes,no,2,36,1,0
12,no,0,30.00000,1.7300,0.000694,0.000000,yes,no,1,42,0,12
13,yes,0,28.83333,2.4500,0.038796,78.874170,yes,no,0,26,1,3
14,yes,0,35.33333,1.9080,0.026907,42.615000,yes,no,2,120,0,5
15,yes,0,41.16667,3.2000,0.125819,335.435000,yes,no,1,168,1,22
16,yes,0,40.08333,4.0000,0.074816,248.719200,yes,no,2,96,1,0
17,no,7,29.50000,3.0000,0.000400,0.000000,yes,no,2,60,1,8
18,yes,0,39.50000,9.9999,0.065795,548.035000,yes,yes,0,28,1,0
19,no,3,45.75000,3.4000,0.000353,0.000000,no,no,0,28,1,10
20,yes,0,35.25000,2.3500,0.022386,43.339170,yes,no,2,115,1,1
21,no,1,25.16667,1.8750,0.000640,0.000000,no,no,2,7,0,2
22,yes,0,34.25000,2.0000,0.131112,218.520000,yes,no,0,12,1,0
23,yes,1,35.75000,4.0000,0.051192,170.640800,no,no,2,18,1,22
24,yes,0,42.66667,5.1400,0.008949,37.583330,yes,no,2,13,1,17
25,yes,0,30.25000,4.5060,0.133742,502.201700,no,no,2,38,1,7
26,no,0,21.66667,3.8400,0.000313,0.000000,no,yes,1,12,0,1
27,yes,0,22.25000,1.5000,0.058608,73.176670,no,no,0,64,1,6
28,no,0,34.25000,2.5000,0.000480,0.000000,yes,no,1,12,1,0
29,yes,0,40.00000,5.5000,0.334460,1532.773000,yes,no,4,74,1,19
...,...,...,...,...,...,...,...,...,...,...,...,...
1289,yes,0,41.41667,3.2000,0.010236,26.878330,no,no,1,16,1,2
1290,yes,0,40.91667,6.0000,0.078964,394.571700,yes,no,0,42,1,5
1291,yes,0,22.00000,1.7500,0.621469,906.309200,no,no,0,2,1,0
1292,no,0,36.00000,4.5000,0.000267,0.000000,yes,no,2,228,1,0
1293,yes,0,39.58333,2.5000,0.192215,400.447500,no,no,0,12,1,4
1294,yes,0,31.58333,2.5500,0.142906,303.674200,no,no,1,60,1,7
1295,yes,0,33.08333,3.2600,0.052736,143.015800,no,no,0,37,1,18
1296,yes,1,22.83333,3.6000,0.048842,146.441700,no,no,0,30,1,20
1297,no,0,35.41667,2.7800,0.000432,0.000000,no,no,0,6,1,0
1298,yes,0,58.08333,4.4000,0.026596,97.184170,yes,yes,1,132,1,12
1299,yes,0,38.75000,3.2000,0.014780,38.997500,yes,no,2,24,1,19
1300,no,0,27.41667,1.6000,0.000750,0.000000,yes,no,1,30,0,0
1301,no,0,23.91667,1.6360,0.000733,0.000000,no,no,1,13,1,0
1302,yes,0,30.08333,2.7000,0.012481,27.416670,no,no,2,1,1,8
1303,yes,0,34.08333,3.5000,0.061674,179.716700,yes,no,0,24,0,10
1304,yes,1,39.08333,3.4224,0.029100,82.659160,yes,no,0,41,1,12
1305,yes,0,38.41667,6.5000,0.029217,157.844200,yes,no,3,60,1,9
1306,yes,0,20.50000,2.0000,0.038431,63.551670,no,no,0,111,1,6
1307,yes,0,35.58333,3.5800,0.051992,154.859200,yes,no,2,123,1,7
1308,yes,0,25.91667,2.5000,0.021250,44.020830,no,no,0,25,1,10
1309,yes,1,40.16667,2.0000,0.254827,424.629200,yes,no,1,121,1,10
1310,yes,0,30.58333,2.5120,0.002627,4.583333,no,yes,3,36,0,4
1311,no,0,39.33333,2.3004,0.000522,0.000000,no,yes,0,46,1,3
1312,no,0,22.58333,3.8600,0.000311,0.000000,no,no,1,36,0,4
1313,no,1,30.33333,2.1800,0.000550,0.000000,no,yes,0,13,1,1
1314,yes,0,33.58333,4.5660,0.002146,7.333333,yes,no,0,94,1,19
1315,no,5,23.91667,3.1920,0.000376,0.000000,no,no,3,12,1,5
1316,yes,0,40.58333,4.6000,0.026513,101.298300,yes,no,2,1,1,2
1317,yes,0,32.83333,3.7000,0.008999,26.996670,no,yes,0,60,1,7
1318,yes,0,48.25000,3.7000,0.111619,344.157500,yes,no,2,2,1,0

In [316]:
#считаем абсолютно точное число дней с заезда на текущее жилье до 2000-01-01
import datetime

#создаем и заполняем list now текущей датой
now = [datetime.date(2000, 1, 1) for i in range(0, len(frame.months))]

#создаем два списка с годом и месяцем (в соотвествии с кол-во месяцев проживания)
then_year = 1999-frame.months//12
then_month = 13-frame.months%12

#если число месяцев делится на 12, frame.months%12 = 0 => исправляем месяц
for i in range(0, len(frame.months)):
    if then_month[i] == 13:
        then_month[i]=1
        
#создаем и заполняем список then с датами заселения по текущему адресу
then = [0 for i in range(0, len(frame.months))]
for i in range(0, len(frame.months)):
    then[i] = datetime.date(then_year[i], then_month[i], 1)
    
#создаем и заполняем список then с числом дней с заселения
days_temp = [0 for i in range(0, len(frame.months))]
for i in range(0, len(frame.months)):
    days_temp[i] = now[i] - then[i]
    
#переводим из формата timedelta в int  
days = [days_temp[i].days for i in range(0, len(frame.months))]

frame_output = frame
frame_output = frame_output.rename(columns={'months': 'days'})
frame_output['days'] = days

#т.к. мы не можем точно определить, работает ли жена(муж) владельца карты (входит ли в dependents),
#будем считать число членов семьи как dependents + 1

frame_output['income_per_family_member'] = frame_output.income / (frame_output.dependents + 1)

#будем разбивать на 5 уровней дохода - до 20 тыс.$, 20-40 тыс.$, 40-60 тыс.$, 60-80 тыс.$, свыше 80 тыс.$.
frame_output['income_level'] = 0

frame_output.loc[frame_output.income<2, 'income_level'] = 1
frame_output.loc[(frame.income>=2) & (frame.income<4), 'income_level'] = 2
frame_output.loc[(frame.income>=4) & (frame.income<6), 'income_level'] = 3
frame_output.loc[(frame.income>=6) & (frame.income<8), 'income_level'] = 4
frame_output.loc[frame.income>8, 'income_level'] = 5

#ВАЖНО!!! в описании ошибка - столбец share - это ежежегодные!!! траты на карту к доходу, т.е.
#expenditure = income * share / 12
#будем считать, что share - ежемесячные траты к ежегодным доходам
frame_output['share_of_annual_expentitures'] = frame_output.share * 12

#датафрейм содержит только тех, у гого share_of_annual_expentitures > 100% (т.е. 1)
frame_output=frame_output[frame_output.share_of_annual_expentitures > 1]

#сортировка списка по share_of_annual_expentitures (сначала идут самозанятые)
frame_output1 = frame_output[frame_output.selfemp=='yes']
frame_output2 = frame_output[frame_output.selfemp=='no']
frame_output1 = frame_output1.sort_values('share_of_annual_expentitures', ascending=False)
frame_output2 = frame_output2.sort_values('share_of_annual_expentitures', ascending=False)

frame_output=frame_output1
frame_output=frame_output.append(frame_output2)

#записываем в файл
writer = pd.ExcelWriter('Output data.xlsx', engine='xlsxwriter')
frame_output.to_excel(writer, sheet_name='OutputData', encoding='utf-8')
writer.save()
frame_output

,card,reports,age,income,share,expenditure,owner,selfemp,dependents,days,majorcards,active,income_per_family_member,income_level,share_of_annual_expentitures
564,yes,0,34.83333,4.0000,0.258251,860.7550,no,yes,0,6574,0,6,4.000000,3,3.099018
351,yes,2,26.00000,7.0000,0.221529,1292.0030,no,yes,0,396,1,31,7.000000,4,2.658348
846,yes,3,27.58333,5.5000,0.220473,1010.5020,no,yes,0,2556,1,11,5.500000,3,2.645677
342,yes,0,56.91667,1.9200,0.200422,320.6758,yes,yes,1,1948,1,9,0.960000,1,2.405069
332,yes,0,34.00000,3.7000,0.189334,583.7783,yes,yes,2,153,1,2,1.233333,2,2.272002
1114,yes,0,37.66667,2.3850,0.167650,332.7042,yes,yes,0,5478,1,13,2.385000,2,2.011799
343,yes,1,34.41667,5.0000,0.164063,683.4283,yes,yes,1,3652,1,6,2.500000,3,1.968754
857,yes,0,26.08333,2.3750,0.142851,282.7258,no,yes,1,3471,1,1,1.187500,2,1.714212
795,yes,0,25.08333,2.8542,0.136232,324.0275,no,yes,1,1279,1,3,1.427100,2,1.634783
892,yes,0,28.50000,4.2320,0.123975,437.1342,no,yes,0,914,1,5,4.232000,3,1.487696
360,yes,0,29.25000,4.4670,0.113949,424.1767,yes,yes,0,1918,1,5,4.467000,3,1.367393
458,yes,1,34.08333,8.1000,0.110766,747.6700,yes,yes,3,1461,1,15,2.025000,5,1.329191
406,yes,0,28.75000,7.0000,0.108352,631.9725,yes,yes,0,730,1,5,7.000000,4,1.300229
748,yes,0,32.33333,6.3000,0.088766,465.9383,no,yes,4,2191,1,7,1.260000,4,1.065192
460,yes,1,33.91667,2.0000,0.906320,1510.5340,no,no,0,730,1,5,2.000000,2,10.875846
623,yes,0,27.16667,2.6000,0.877846,1902.0000,no,no,0,122,1,7,2.600000,2,10.534153
1180,yes,0,23.16667,2.6000,0.824551,1786.2770,no,no,0,122,1,0,2.600000,2,9.894610
1291,yes,0,22.00000,1.7500,0.621469,906.3092,no,no,0,61,1,0,1.750000,1,7.457629
586,yes,1,29.83333,3.7000,0.595776,1836.9760,no,no,0,1095,1,7,3.700000,2,7.149312
1041,yes,0,20.83333,1.8000,0.553518,830.2767,no,no,0,153,0,0,1.800000,1,6.642214
865,yes,0,22.75000,1.8200,0.541860,821.8208,no,no,0,2831,1,2,1.820000,1,6.502319
559,yes,0,34.25000,3.0000,0.540995,1352.4880,yes,no,0,2556,1,3,3.000000,2,6.491944
1030,yes,0,32.66667,3.6500,0.538365,1637.5270,yes,no,1,975,1,7,1.825000,2,6.460379
466,yes,0,29.00000,2.5000,0.526396,1096.6570,no,no,0,730,1,14,2.500000,2,6.316747
1171,yes,0,30.16667,2.1900,0.487444,889.5850,no,no,0,184,1,0,2.190000,2,5.849326
56,yes,0,34.33333,4.8000,0.474508,1898.0330,no,no,3,730,1,1,1.200000,3,5.694100
762,yes,0,35.25000,6.0000,0.458235,2291.1740,no,no,2,306,1,0,2.000000,4,5.498818
897,yes,0,25.25000,1.8000,0.455992,683.9883,yes,no,0,2983,1,2,1.800000,1,5.471908
1063,yes,0,34.91667,5.0000,0.425845,1774.3560,yes,no,3,1461,1,7,1.250000,3,5.110145
1212,yes,0,22.83333,2.5000,0.402864,839.3008,no,no,0,122,1,1,2.500000,2,4.834373
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,yes,0,28.08333,2.1000,0.090680,158.6067,yes,no,1,1095,0,11,1.050000,2,1.088160
453,yes,0,45.08333,3.9000,0.090640,294.5800,no,no,0,4017,1,12,3.900000,2,1.087680
1116,yes,0,31.75000,2.0070,0.090453,151.0325,no,no,1,122,1,0,1.003500,2,1.085435
648,yes,0,30.66667,4.0000,0.090116,299.8858,yes,no,1,1126,0,6,2.000000,3,1.081389
1068,yes,0,25.41667,2.4500,0.090071,183.5608,no,no,0,1826,1,6,2.450000,2,1.080847
1164,yes,1,32.75000,6.0000,0.089808,449.0392,no,no,0,184,0,17,6.000000,4,1.077694
672,yes,0,25.16667,1.5000,0.089805,111.8392,yes,no,1,426,1,19,0.750000,1,1.077656
464,yes,0,27.91667,2.5200,0.089612,188.1858,no,no,1,730,1,0,1.260000,2,1.075348
237,yes,0,20.50000,1.5400,0.089597,114.8158,no,no,0,184,1,2,1.540000,1,1.075161
34,yes,0,23.83333,3.0000,0.089016,222.5392,no,no,0,730,1,5,3.000000,2,1.068188
633,yes,0,27.16667,2.5000,0.088773,184.9433,no,no,0,730,1,8,2.500000,2,1.065274
155,yes,0,49.66667,2.7000,0.088770,199.7333,yes,no,0,4017,0,3,2.700000,2,1.065244
797,yes,0,29.41667,3.6500,0.087895,267.3483,no,no,0,1095,1,17,3.650000,2,1.054744
675,yes,0,23.16667,2.8500,0.087458,207.7133,yes,no,1,1522,0,8,1.425000,2,1.049499
1262,yes,1,25.25000,2.9000,0.086867,209.8442,no,no,0,8766,1,6,2.900000,2,1.042399
1232,yes,0,31.08333,2.8000,0.086844,202.4700,yes,no,3,457,1,17,0.700000,2,1.042131
255,yes,0,21.58333,3.1200,0.086779,225.4592,no,no,1,306,0,6,1.560000,2,1.041350
1216,yes,0,34.16667,9.2000,0.086624,664.1208,yes,no,5,2466,1,7,1.533333,5,1.039494
1001,yes,1,38.83333,2.5200,0.086467,181.4142,yes,no,0,4201,1,8,2.520000,2,1.037605
219,yes,0,26.08333,3.5000,0.085950,250.5208,no,no,0,1583,1,2,3.500000,2,1.031400
716,yes,0,28.66667,4.2200,0.085591,300.9942,yes,no,1,671,1,3,2.110000,3,1.027089
571,yes,0,33.16667,5.6000,0.085296,398.0475,yes,no,4,2922,1,4,1.120000,3,1.023551
1197,yes,0,24.91667,2.3000,0.085194,163.0392,no,no,0,791,1,7,2.300000,2,1.022332
780,yes,0,25.91667,3.7000,0.084364,260.1208,yes,no,0,7184,1,6,3.700000,2,1.012362
607,yes,0,31.00000,2.6000,0.084193,182.1675,no,no,0,153,1,0,2.600000,2,1.010312
585,yes,0,19.41667,1.8000,0.084150,125.8917,no,no,0,92,1,0,1.800000,1,1.009800
975,yes,0,57.58333,4.1000,0.083899,286.5700,yes,no,3,3683,1,15,1.025000,3,1.006782
244,yes,0,20.50000,1.6000,0.083832,111.6925,no,no,0,92,1,0,1.600000,1,1.005983
1057,yes,0,24.00000,2.1000,0.083678,146.2700,yes,no,0,1095,1,14,2.100000,2,1.004137
1076,yes,0,29.25000,1.8000,0.083366,124.6325,no,no,0,1553,1,3,1.800000,1,1.000393

### Задача 2

Выведите на экран или запишите в отдельный файл следующую информацию о датафрейме,созданном без учета фильтрации в Задаче 1:
- Среднее количество dependents для людей, которые не являются собственниками жилья.
- Средний возраст для каждого уровня доходов согласно выбранной вами классификации.
- Топ 5 самых молодых и самых пожилых людей, чью заявку на кредитную карту не удовлетворили.
- Среднее количество major credit cards для 10 людей, обладающих самым высоким доходом.

In [317]:
#Среднее количество dependents для людей, которые не являются собственниками жилья.
import statistics
print ('Среднее кол-во dependents для не собственников жилья: '
+str(statistics.mean(frame[frame.owner == 'no'].dependents)))

Среднее кол-во dependents для не собственников жилья: 0.6517615176151762

In [318]:
#Средний возраст для каждого уровня доходов согласно выбранной вами классификации.
#будем разбивать на 5 уровней дохода - до 20 тыс.$, 20-40 тыс.$, 40-60 тыс.$, 60-80 тыс.$, свыше 80 тыс.$.
import statistics
print ('Средний возраст для уровня доходов 1 (до 20 тыс. $): ' 
       + str(statistics.mean(frame[(frame.income<2)].age)))
print ('Средний возраст для уровня доходов 2 (от 20 до 40 тыс. $): '
       + str(statistics.mean(frame[(frame.income>=2) & (frame.income<4)].age)))
print ('Средний возраст для уровня доходов 3 (от 40 до 60 тыс. $): ' 
       + str(statistics.mean(frame[(frame.income>=4) & (frame.income<6)].age)))
print ('Средний возраст для уровня доходов 4 (от 60 до 80 тыс. $): ' 
       + str(statistics.mean(frame[(frame.income>=6) & (frame.income<8)].age)))
print ('Средний возраст для уровня доходов 5 (свыше 80 тыс. $): ' 
       + str(statistics.mean(frame[frame.income>=8].age)))

Средний возраст для уровня доходов 1 (до 20 тыс. $): 29.38281265625
Средний возраст для уровня доходов 2 (от 20 до 40 тыс. $): 31.95157223899371
Средний возраст для уровня доходов 3 (от 40 до 60 тыс. $): 37.62389351017699
Средний возраст для уровня доходов 4 (от 60 до 80 тыс. $): 39.77816887323944
Средний возраст для уровня доходов 5 (свыше 80 тыс. $): 41.08095171428571

In [319]:
#Топ 5 самых молодых людей, чью заявку на кредитную карту не удовлетворили.
print ('Топ-5 самых молодых, чью заявку не одобрили: ')
frame[frame.card=='no'].sort_values('age').head(5)

Топ-5 самых молодых, чью заявку не одобрили:

,card,reports,age,income,share,expenditure,owner,selfemp,dependents,months,majorcards,active
461,no,0,0.75000,3.00,0.000400,0.0,no,no,0,18,0,2
544,no,0,19.00000,1.97,0.000609,0.0,no,no,1,24,1,2
1268,no,0,19.41667,2.20,0.000545,0.0,no,no,0,6,1,0
1189,no,0,19.50000,1.56,0.000769,0.0,yes,no,0,46,0,3
964,no,0,19.58333,2.10,0.000571,0.0,no,no,0,124,1,2

In [320]:
#Топ 5 самых пожилых людей, чью заявку на кредитную карту не удовлетворили.
print ('Топ-5 самых пожилых, чью заявку не одобрили: ')
frame[frame.card=='no'].sort_values('age',ascending=False).head(5)

Топ-5 самых пожилых, чью заявку не одобрили:

,card,reports,age,income,share,expenditure,owner,selfemp,dependents,months,majorcards,active
986,no,0,80.16666,1.5000,0.000800,0.0,no,no,0,24,1,0
1175,no,0,69.75000,1.8000,0.000667,0.0,yes,no,0,528,0,5
695,no,0,66.50000,3.2500,0.000369,0.0,yes,no,3,300,1,13
1122,no,1,63.41667,2.1375,0.000561,0.0,yes,no,0,240,1,7
207,no,6,62.91667,2.5500,0.000471,0.0,no,no,2,20,0,13

In [321]:
#Среднее количество major credit cards для 10 людей, обладающих самым высоким доходом.
import statistics
print('Среднее количество major credit cards у топ-10 с самым высоким доходом:')
statistics.mean(frame.sort_values('income',ascending=False).head(10).majorcards)

Среднее количество major credit cards у топ-10 с самым высоким доходом:

0.9